# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: consul.hashicorp.com/v1alpha1
kind:  ServiceIntentions
metadata:
  name: postgres
  namespace: default
spec:
  sources:
    - name:  "products-api"
      action: "allow"
      namespace: "default"
      partition: "tereknor"
  destination:
    name: postgres
    namespace: default