global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.12.2
  imageEnvoy: envoyproxy/envoy:v1.22.2
  imageK8S: hashicorp/consul-k8s-control-plane:0.45.0
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
prometheus:
  enabled: true
