global:
  name: server
  image: 'hashicorp/consul-enterprise:1.22.7-ent'
  enableConsulNamespaces: true
  # The name of the datacenter. Admin partitions are only supported in the same datacenter today.
  datacenter: dc1
  enterpriseLicense:
    # The Kubernetes secret key/value pair for your Consul Enterprise license. If using the terraform project provided with this tutorial
    # this license is automatically uploaded for you as a secret if you place the license inside the `consul_enterprise` folder before deploying.
    secretName: 'consul-ent-license'
    secretKey: 'key'
  # The stanza that sets up Admins Partitions and the reason you are reading this tutorial :)
  adminPartitions:
    enabled: true
    service:
      annotations: |
        "service.beta.kubernetes.io/aws-load-balancer-scheme": "internal"
  acls:
    manageSystemACLs: true
  logLevel: 'debug'
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    verify: false
    enableAutoEncrypt: true
    serverAdditionalDNSSANs:
      # Subject Alternative Names that the TLS certificate will validate. In this case,
      # these are wildcard values for Amazon EKS and Elastic Load Balancer services suppporting this tutorial.
      # Note that wildcard values are not recommended for use in production environments.
      - '*.us-east-1.elb.amazonaws.com'
      - '*.gr7.us-east-1.eks.amazonaws.com'
server:
  storageClass: "ebs-sc"
  exposeGossipAndRpcPorts: true
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  aclBindingRuleSelector: ''
  consulNamespaces:
    mirroringK8S: true
  transparentProxy:
    defaultEnabled: true
  centralConfig:
    enabled: true
controller:
  enabled: true
dns:
  enabled: true
  enableRedirection: true
meshGateway:
  enabled: true