global:
  name: consul
  datacenter: dc1
  image: "hashicorpdev/consul:1.11.2"
  tls:
    enabled: true
    serverAdditionalDNSSANs:
    - host.docker.internal
    - localhost
    - consul-server.default.svc.cluster.local
server:
  replicas: 1
ui:
  enabled: true
  service:
    type: 'NodePort'
connectInject:
  enabled: true
controller:
  enabled: true
